return {
	AnimationId = "rbxassetid://-",
	Available = true,
	ImageIcon = "rbxassetid://-",
	IsActiveSkill = true,
	PercentagePerLevel = {
	  22,
	  22.4,
	  22.8,
	  23.2,
	  23.6,
	  24,
	  24.4,
	  24.8,
	  25.2,
	  25.6,
	  26,
	  26.4,
	  26.8,
	  27.2,
	  27.6,
	  28,
	  28.4,
	  28.8,
	  29.2,
	  29.6,
	  30,
	  30.4,
	  30.8,
	  31.4,
	},
	SkillCooldown = 5,
	SkillDescription = "<font color = '#ff9900'><b>TAP:</b></font> Natsuko will briefly uppercut once in front of her, dealing <font color = '#ff8000'>damage</font> to enemies struck in its minuscule range.\
  \
  <font color = '#ff9900'><b>HOLD:</b></font> Charge up a devastating attack. If this stance has held for at least three seconds, release to flare Natsuko upwards, dealing <font color = '#ff8000'>draconic amounts of damage</font> to enemies caught within its radiance.",
	SkillGoldCost = 10000,
	SkillLevelReq = 50,
	SkillName = "Dragon Punch",
	SkillPrefix = "% DMG",
	SkillStamCost = 130,
  }