return {
	AnimationId = "rbxassetid://-",
	Available = true,
	ImageIcon = "rbxassetid://-",
	IsActiveSkill = true,
	PercentagePerLevel = {
	  -0.7,
	  -0.71,
	  -0.72,
	  -0.73,
	  -0.74,
	  -0.75,
	  -0.76,
	  -0.78,
	  -0.79,
	  -0.8,
	  -0.81,
	  -0.82,
	  -0.83,
	  -0.84,
	  -0.85,
	  -0.86,
	  -0.87,
	  -0.88,
	  -0.89,
	  -0.9,
	  -0.92,
	  -0.94,
	  -0.96,
	  -1,
	},
	SkillCooldown = 4,
	SkillDescription = "<font color = '#ffffff'>Reduces damage taken</font> for one second. Getting hit during this time will grant <font color = '#ffffff'>35 Combo Score</font> and <font color = '#ffffff'>50% additional attack speed for 10 seconds</font>.\
  \
  Mobs who strike Darwin during this time will be dealt <font color = '#ff8000'>5% of their current health</font> as <font color = '#ff8000'>bonus damage</font>. Bosses instead take <font color = '#ff8000'>0.75% of their MAX HP</font> as <font color = '#ff8000'>bonus damage</font>.",
	SkillGoldCost = 1800,
	SkillLevelReq = 15,
	SkillName = "Elysian Counter",
	SkillPrefix = "% DMG taken",
	SkillStamCost = 25,
  }