return {
	AnimationId = "rbxassetid://-",
	Available = true,
	ImageIcon = "rbxassetid://-",
	IsActiveSkill = true,
	PercentagePerLevel = {
	  0.05,
	  0.07,
	  0.09,
	  0.11,
	  0.13,
	  0.15,
	  0.17,
	  0.19,
	  0.21,
	  0.23,
	  0.25,
	  0.26,
	  0.27,
	  0.28,
	  0.29,
	  0.3,
	  0.31,
	  0.32,
	  0.33,
	  0.34,
	  0.35,
	  0.36,
	  0.37,
	  0.38,
	},
	SkillCooldown = 1,
	SkillDescription = "Burst a disseminating barrage of beams that bounce off of nearby surfaces. Outlying beams that reach at least <font color = '#ffffff'>50 - 70 studs</font> away from Valeri and have not yet bounced from a surface will be bounced back towards the nearest enemy. \
  \
  <font color = '#ff9900'><b>EMPOWERED BONUS:</b></font> All beams, upon bouncing once, will immediately target the closest enemy and deal <font color = '#ff8000'>100% bonus damage</font>.\
  \
  <font color = '#6b7687'><i>Valeri launches 30 beams total—each can bounce up to five times before disappearing.</i></font>",
	SkillGoldCost = 1800,
	SkillLevelReq = 15,
	SkillName = "Ricochet Beams",
	SkillPrefix = "% DMG per beam",
	SkillStamCost = 70,
  }