return {
	AnimationId = "rbxassetid://-",
	Available = true,
	ImageIcon = "rbxassetid://-",
	IsActiveSkill = true,
	PercentagePerLevel = {
	  0.6,
	  0.7,
	  0.8,
	  0.9,
	  1,
	  1.1,
	  1.2,
	  1.3,
	  1.35,
	  1.4,
	  1.45,
	  1.5,
	  1.55,
	  1.6,
	  1.65,
	  1.7,
	  1.75,
	  1.8,
	  1.85,
	  1.9,
	  1.95,
	  2,
	  2.05,
	  2.1,
	},
	SkillCooldown = 6,
	SkillDescription = "Slams the ground in front of you, dealing <font color = '#ff8000'>damage</font> to surrounding enemies multiple times. This skill will consume <font color = '#fc6a6a'>20% of your current HP</font> upon use.\
  \
  Pierced enemies will take <font color = '#ff8000'>double damage</font> and hitting Pierced enemies regens <font color = '#42ff49'>2.5% of your MAX HP</font> per hit.\
  \
  <font color = '#6b7687'><i>This skill will make you invulnerable for the duration of its animation.</i></font>",
	SkillGoldCost = 5000,
	SkillLevelReq = 30,
	SkillName = "Reign Matrix",
	SkillPrefix = "% DMG",
	SkillStamCost = 130,
	SkillTooltipDescription = "",
  }