return {
	AnimationId = "rbxassetid://-",
	Available = true,
	ImageIcon = "rbxgameasset://-",
	IsActiveSkill = true,
	PercentagePerLevel = {
	  0.05,
	  0.1,
	  0.15,
	  0.2,
	  0.25,
	  0.3,
	  0.35,
	  0.4,
	  0.45,
	  0.5,
	  0.55,
	  0.6,
	  0.65,
	  0.7,
	  0.8,
	  1,
	  1.2,
	  1.4,
	  1.6,
	  1.8,
	  2,
	  2.2,
	  2.4,
	  2.8,
	},
	SkillCooldown = 3,
	SkillDescription = "Red pulls the pin on a grenade, and after a delay, rains shrapnel around Red which slowly expands.\
  \
  While under a shrapnel cloud, Red slowly regenerates her max HP equal to <font color = '#ffffff'>0.03% of her current Critical Wounds</font>.\
  \
  <font color = '#6b7687'><i>This skill remains in place after use for five seconds.</i></font>",
	SkillGoldCost = 1800,
	SkillLevelReq = 15,
	SkillName = "Grenade Throw",
	SkillPrefix = "% DMG",
	SkillStamCost = 15,
  }