return {
	AnimationId = "rbxassetid://-",
	Available = true,
	ImageIcon = "rbxgameasset://-",
	IsActiveSkill = true,
	PercentagePerLevel = {
	  1,
	  1.3,
	  1.6,
	  1.9,
	  2.2,
	  2.5,
	  2.8,
	  3.1,
	  3.4,
	  3.5,
	  3.52,
	  3.54,
	  3.56,
	  3.58,
	  3.6,
	  3.62,
	  3.64,
	  3.66,
	  3.68,
	  3.7,
	  3.72,
	  3.74,
	  3.76,
	  3.78,
	},
	SkillCooldown = 0,
	SkillDescription = "Aim in the direction of your cursor. The rifle will automatically charge up, with the fired shot dealing <font color = '#ff8000'>more damage per second</font>, up to five seconds.\
  \
  This skill guarantees Crits on near Max Charge. Can <font color = '#ff8000'>damage</font> nearby enemies from the target.\
  \
  Every 1% Attack Speed increases Take Aim <font color = '#ff8000'>damage by 0.5%</font>.",
	SkillGoldCost = 0,
	SkillLevelReq = 0,
	SkillName = "Take Aim",
	SkillPrefix = "% DMG per sec charged",
	SkillStamCost = 25,
  }